### ISSUE TITLE
unknown command "dependency" for "helm-x"

### ISSUE THREAD

**Issue by acaire** [mumoshu/helm-x#23]
Hi, just testing this out, and having an issue when `helm-x` runs `helm dependency`

```
./helm-x dependency
I0718 16:49:13.243063   16344 helm_fallback.go:40] helm-x: executing helm dependency
I0718 16:49:13.243561   16344 cmdsite.go:47] running /usr/local/bin/helm dependency
F0718 16:49:13.306316   16344 main.go:51] unknown command "dependency" for "helm-x"
```

I've stepped through the code, this just seems like it's always going to always throw an error?
https://github.com/mumoshu/helm-x/blob/9c52715de9f48d756fb5a9dc1c674b7796634ee0/main.go#L49-L52

**Comment by voor** [comment]
Big fan of using the `helm diff` plugin which does work with `helmfile`, and this breaks that functionality.

**Comment by cferrera** [comment]
facing the same issue here. did you find any solution?

**Comment by acaire** [comment]
Closing this issue now as the functionality that I need is now baked into Helmfile.

**Comment by schue** [comment]
Is it no longer necessary to specify --helm-binary when running helmfile?

**Comment by SCLogo** [comment]
same issue here. Any updates on this?

**Comment by SCLogo** [comment]
without --helm-binary I got the following error:
exec: "kustomize": executable file not found in $PATH
